/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.*;
import java.awt.*;

public class App_def {

    private JFrame frame;

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            App_def app = new App_def();
            app.init();
            app.frame.setVisible(true);
        });
    }

    public void init() {
        frame = new JFrame("App");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 600);

        GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();

        if (device.isFullScreenSupported()) {
            frame.setUndecorated(true);
            device.setFullScreenWindow(frame);
        } else {
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            frame.setUndecorated(true);
        }

        JPanel panel = new JPanel(new BorderLayout());
        panel.add(Tools.createButton("HI"), BorderLayout.CENTER);
        frame.getContentPane().add(panel, BorderLayout.CENTER);
    }
}
